// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQzKlmEJQRUkVJLhfPnY3M6BloxW3bXDw',
    appId: '1:561645060195:web:a429a3a6afef16ff227856',
    messagingSenderId: '561645060195',
    projectId: 'memeapp-758a4',
    authDomain: 'memeapp-758a4.firebaseapp.com',
    storageBucket: 'memeapp-758a4.firebasestorage.app',
    measurementId: 'G-L1TBQNNQYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUeIY15SyTvqEaVXaj-0Jexr5PmCgkcBU',
    appId: '1:561645060195:android:3eb0ca4bc98571be227856',
    messagingSenderId: '561645060195',
    projectId: 'memeapp-758a4',
    storageBucket: 'memeapp-758a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_d1_Pbt37EpramxzI1j_gRRK-as7RAM',
    appId: '1:561645060195:ios:887857f2168b6b6c227856',
    messagingSenderId: '561645060195',
    projectId: 'memeapp-758a4',
    storageBucket: 'memeapp-758a4.firebasestorage.app',
    iosBundleId: 'com.example.memeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_d1_Pbt37EpramxzI1j_gRRK-as7RAM',
    appId: '1:561645060195:ios:887857f2168b6b6c227856',
    messagingSenderId: '561645060195',
    projectId: 'memeapp-758a4',
    storageBucket: 'memeapp-758a4.firebasestorage.app',
    iosBundleId: 'com.example.memeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQzKlmEJQRUkVJLhfPnY3M6BloxW3bXDw',
    appId: '1:561645060195:web:25e53b555d4fc212227856',
    messagingSenderId: '561645060195',
    projectId: 'memeapp-758a4',
    authDomain: 'memeapp-758a4.firebaseapp.com',
    storageBucket: 'memeapp-758a4.firebasestorage.app',
    measurementId: 'G-VGMT1X4KDM',
  );
}
